# Generated by Django 5.2.6 on 2026-09-30 09:08

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loan', '0004_loan_request_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repayment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=13)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayments', to='loan.loan')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_repayments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'repayment',
                'ordering': ('-paid_at', '-id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('principal_amount__gt', 0)), name='repayment_principal_positive'), models.CheckConstraint(condition=models.Q(('interest_amount__gte', 0)), name='repayment_interest_nonnegative'), models.CheckConstraint(condition=models.Q(('total_amount', django.db.models.expressions.CombinedExpression(models.F('principal_amount'), '+', models.F('interest_amount')))), name='repayment_total_matches_components')],
            },
        ),
    ]
