# Generated by Django 5.2.6 on 2026-09-30 10:04

from django.conf import settings
from django.db import migrations, models


def sequence_existing_repayments(apps, schema_editor):
    Repayment = apps.get_model('repayment', 'Repayment')
    last_installment_by_loan = {}
    repayments = Repayment.objects.order_by('loan_id', 'paid_at', 'pk')
    for repayment in repayments.iterator():
        installment_number = last_installment_by_loan.get(repayment.loan_id, 0) + 1
        repayment.installment_number = installment_number
        repayment.save(update_fields=('installment_number',))
        last_installment_by_loan[repayment.loan_id] = installment_number


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_loan_repayment_term_months_and_more'),
        ('repayment', '0002_repayment_transaction_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment',
            name='installment_number',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.RunPython(sequence_existing_repayments, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='repayment',
            constraint=models.CheckConstraint(condition=models.Q(('installment_number__gte', 1)), name='repayment_installment_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='repayment',
            constraint=models.UniqueConstraint(fields=('loan', 'installment_number'), name='unique_loan_repayment_installment'),
        ),
    ]
