# Generated by Django 5.2.6 on 2026-09-28 11:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contribution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FundAccount',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('available_funds', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fund_account',
                'constraints': [models.CheckConstraint(condition=models.Q(('available_funds__gte', 0)), name='fund_account_available_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('transaction_id', models.CharField(blank=True, editable=False, max_length=40, null=True, unique=True)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.CharField(blank=True, max_length=255)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loan',
                'ordering': ('-requested_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='FundLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('OPENING_BALANCE', 'Opening balance'), ('CONTRIBUTION_RECEIVED', 'Contribution received'), ('CONTRIBUTION_CANCELLED', 'Contribution cancelled'), ('LOAN_APPROVED', 'Loan approved')], max_length=24)),
                ('direction', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='loan.fundaccount')),
                ('contribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fund_ledger_entries', to='contribution.contribution')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fund_ledger_entries', to='loan.loan')),
            ],
            options={
                'db_table': 'fund_ledger_entry',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('requested_amount__gt', 0)), name='loan_requested_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ('PENDING', 'REJECTED')), ('transaction_id__isnull', True)), models.Q(('status__in', ('APPROVED', 'COMPLETED')), ('transaction_id__isnull', False)), _connector='OR'), name='loan_transaction_id_matches_status'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('PENDING', 'APPROVED'))), fields=('employee',), name='one_active_loan_per_employee'),
        ),
        migrations.AddConstraint(
            model_name='fundledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='fund_ledger_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='fundledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'LOAN_APPROVED')), fields=('loan',), name='one_loan_approval_ledger_entry'),
        ),
        migrations.AddConstraint(
            model_name='fundledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'CONTRIBUTION_RECEIVED')), fields=('contribution',), name='one_contribution_credit_entry'),
        ),
        migrations.AddConstraint(
            model_name='fundledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'CONTRIBUTION_CANCELLED')), fields=('contribution',), name='one_contribution_cancel_entry'),
        ),
    ]
