# Generated by Django 5.2.6 on 2026-09-30 10:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_loan_request_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='repayment_term_months',
            field=models.PositiveSmallIntegerField(default=12),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('repayment_term_months__gte', 1), ('repayment_term_months__lte', 12)), name='loan_term_between_1_and_12_months'),
        ),
    ]
