# Generated by Django 6.1.1 on 2026-09-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0002_alter_employee_managers_remove_employee_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='username',
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
